[sender]
# Use throwaway or spare account for security purposes
# Alternatively, store these in system's evnironment variables
email_address = " "
password = " "
server = "smtp.gmail.com"

# TODO: Nested Table for receivers
