[sender]
# Use throwaway or spare account for security purposes
# Alternatively, store these in system's evnironment variables
email_address = "fcbjh0204@gmail.com"
password = "gcrgvirmtfcnnyan"
server = "smtp.gmail.com"

[directories]
attachments = "\\attachments"
email_script = "\\email_script"

# TODO: Nested Table for receivers
