[sender]
# Use throwaway or spare account for security purposes
# Alternatively, store these in system's evnironment variables
email_address = ""
password = "gcrgvirmtfcnnyan"
server = "smtp.gmail.com"

[directories]
attachments = "\\attachments"
email_script = "\\email_script"
email_list = "\\email_list"

[email_content]
short_name = "Jun Hui"
full_name = "Au Jun Hui"


